name: Compile LaTeX Documents  

on: [push]

permissions:
    contents: write
    
jobs:
    build_latex:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4
          - name: Compile Resume document
            uses: xu-cheng/latex-action@v3
            with:
                root_file: '**/*.tex'
                work_in_root_file_dir: true
                continue_on_error: true
                latexmk_shell_escape: true
          - name: Rename PDFs According to JobName
            run: |
                find . -type f -iname "*.pdf" | while read fname; do
                    dirname=`dirname $fname`
                    filename=`basename $fname`
                    texname=`echo $filename | sed 's/pdf/tex/'`
                    newname=`head -n 1 $dirname/$texname`
                    newname="${newname##*=}.pdf"
                    mv "${dirname}/$filename" "${dirname}/${newname}"
                done
          - name: Upload Artifacts
            uses: actions/upload-artifact@master
            with:
                name: pdf_files
                path: '**/*.pdf'
          - name: Create Latest Release
            uses: softprops/action-gh-release@v2.0.9
            with:
                files: "**/*.pdf"
                name: Latest
                tag_name: latest
                make_latest: true
          - name: Create Tagged Release
            if: startsWith(github.ref, 'refs/tags/')
            uses: softprops/action-gh-release@v2.0.9
            with:
                files: "**/*.pdf"
                generate_release_notes: true
                make_latest: true