name: Compile LaTeX Documents  

on: [push, workflow_dispatch]

permissions:
    contents: write
    
jobs:
    latex_release:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4.2.2
          - name: Get Project List
            run: |
                mkdir -p projects
                gh repo list -L 200 --json \
                name,description,createdAt,updatedAt,\
                forkCount,stargazerCount,watchers,languages,\
                primaryLanguage,repositoryTopics,isArchived,\
                isFork,isPrivate,isTemplate \
                $OWNER > projects/repoList.json
            env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                OWNER: ${{ github.repository_owner }}
          - name: Get Project Readmes
            run: |
                gh repo list -L 200 $OWNER > repos
                mkdir projects/$OWNER
                awk '{print $1}' repos | while read line ; do \
                mkdir -p projects/$line ; \
                curl -o projects/$line/README.md https://raw.githubusercontent.com/$line/refs/heads/main/documents/README.md ; \
                done
            env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                OWNER: ${{ github.repository_owner }}
          - name: Import GPG Key
            uses: crazy-max/ghaction-import-gpg@cb9bde2e2525e640591a934b1fd28eef1dcaf5e5
            with:
                gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                passphrase: ${{ secrets.PASSPHRASE }}
                trust_level: 5
          - name: Decrypt Signature Image
            run: |
                gpg -d -o templates/signature.tar templates/signature.tar.gpg
                tar -xvf templates/signature.tar --directory templates
          - name: Compile Latex documents
            uses: xu-cheng/latex-action@v3
            continue-on-error: true
            with:
                root_file: '**/*.tex'
                work_in_root_file_dir: true
                continue_on_error: true
                latexmk_shell_escape: true
                latexmk_use_lualatex: true
          - name: Rename PDFs According to JobName
            run: |
                find . -type f -iname "*.pdf" | while read fname; do
                    dirname=`dirname $fname`
                    filename=`basename $fname`
                    texname=`echo $filename | sed 's/pdf/tex/'`
                    if [ -f '$dirname/$texname' ]; then
                        newname=`head -n 1 $dirname/$texname`
                        newname="${newname##*=}.pdf"
                        if [ $newname != '.pdf' ]; then
                            mv "${dirname}/$filename" "${dirname}/${newname}"
                        fi
                    fi
                done
          - name: Digitally Sign PDF Documents
            env:
                secret_passphrase: ${{ secrets.PASSPHRASE }}
            if: ${{ env.secret_passphrase != '' }}
            run: |
                find . -type f -iname "*.pdf" | while read fname; do
                    dirname=`dirname $fname`
                    filename=`basename $fname`
                    gpg --pinentry-mode loopback --passphrase ${{ secrets.PASSPHRASE }} --clearsign --not-dash-escaped "${dirname}/$filename"
                    mv "${dirname}/$filename".asc "${dirname}/$filename"
                    gpg --pinentry-mode loopback --passphrase ${{ secrets.PASSPHRASE }} --detach-sig "${dirname}/$filename"
                done
          - name: Delete Previous Release
            run: gh release delete latest --cleanup-tag
            continue-on-error: true
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          - name: Create Latest Release (always)
            uses: softprops/action-gh-release@v2.1.0
            with:
                files: |
                    **/*.pdf
                    **/*.sig
                name: latest
                tag_name: latest
                make_latest: true
                body: Personal Documents Compiled via LaTeX
          - name: Create Tagged Release (if push is tagged)
            if: startsWith(github.ref, 'refs/tags/')
            uses: softprops/action-gh-release@v2.0.9
            with:
                files: |
                    **/*.pdf
                    **/*.sig
                generate_release_notes: true
                make_latest: true
                body: Personal Documents Compiled via LaTeX